version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: media_manifest_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: media_manifest
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: elbrus_reach_backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/media_manifest
    depends_on:
      - mongodb
    restart: unless-stopped