services:
  mongodb:
    image: mongo:latest
    container_name: media_manifest_db
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASSWORD}
      MONGO_INITDB_DATABASE: media_manifest
    restart: unless-stopped

  backend:
    build: ./app/backend
    container_name: elbrus_reach_backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/media_manifest
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build: ./app/frontend/dashboard
    container_name: elbrus_reach_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_server
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./data/prometheus_data:/prometheus
    environment:
      SERVICE_NAME: prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      - prometheus
    restart: unless-stopped